export const types = {
  GET_STORIES_ID_REQUEST: 'GET_STORIES_ID_REQUEST',
  GET_STORIES_ID_SUCCESS: 'GET_STORIES_ID_SUCCESS',
  GET_STORIES_ID_FAILED: 'GET_STORIES_ID_FAILED',
  RESET_STORIES_ID_ERROR: 'RESET_STORIES_ID_ERROR',
};

export interface StoriesIdState {
  storiesId: StoreFetchState<number[]>;
}
